auth_login/urls.py
from django.urls import path
from auth_login import views

app_name = 'auth'

urlpatterns = [
	path('login', views.login, name='login'),
	path('logout', views.logout, name='logout'),
]

basket/urls.py
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [
	path('', views.list , name='list'),
	path('teams', views.team_list , name='team_list'),
	path('players', views.player_list , name='player_list'),
	path('coach', views.coach_list , name='coach_list'),
	path('match', views.match_list , name='match_list'),
	path('create_team', views.create_team , name='create_team'),
	path('update_team/<int:team_id>', views.update_team , name='update_team'),
	path('delete_team/<int:team_id>', views.delete_team , name='delete_team'),
	path('create_player', views.create_player , name='create_player'),
	path('update_player/<int:player_id>', views.update_player , name='update_player'),
	path('delete_player/<int:player_id>', views.delete_player , name='delete_player'),
	path('create_coach', views.create_coach , name='create_coach'),
	path('update_coach/<int:coach_id>', views.update_coach , name='update_coach'),
	path('delete_coach/<int:coach_id>', views.delete_coach , name='delete_coach'),
	path('update_coach_password', views.update_coach_password , name='update_coach_password'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls')), #todas las urls que tengan basket van a pasar por urls.py alojado en la carpeta de basket
    path('auth/', include('auth_login.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models
from django.contrib.auth.models import User


"""
Nombre entrenador
Edad
Email
Rut
Apodo
"""
class Coach(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    age = models.PositiveIntegerField()
    email = models.EmailField()
    rut = models.CharField(max_length=12)
    nickname = models.CharField(max_length=80)

    def __str__(self):
        return self.name

"""
Nombre del team
Descripción del team
Logo del team
Código de equipo
"""
class Team(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    code = models.CharField(max_length=20, unique=True)
    logo = models.ImageField(upload_to='teams/', blank=True, null=True)
    coach = models.OneToOneField(Coach, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

"""
Nombre jugador
Apodo
Fecha de nacimiento
Edad
Rut
Email
Estatura
Peso
Fotografía
Posición de juego (opciones: Base, Escolta, Alero, Ala-pivot, Pivot)
"""

POSITION_PLAYER = (
    ('BA', 'Base'),
    ('ES', 'Escolta'),
    ('AL', 'Alero'),
    ('AP', 'Ala-pivot'),
    ('PI', 'Pivot'),
)

class Player(models.Model):
    name = models.CharField(max_length=150)
    nickname = models.CharField(max_length=80)
    birthday = models.DateField()
    age = models.PositiveIntegerField()
    rut = models.CharField(max_length=12)
    email = models.EmailField()
    height = models.PositiveIntegerField(help_text='in centimeters')
    weight = models.PositiveIntegerField(help_text='in grams')
    photo = models.ImageField(upload_to='players/', blank=True, null=True)
    position = models.CharField(choices=POSITION_PLAYER, max_length=2)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return '{name} ({team})' . format(name=self.name, team=self.team)



class Roster(models.Model):
    name = models.CharField(max_length=150)
    team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)
    player = models.ManyToManyField(Player)

    def __str__(self):
        return self.name


class Match(models.Model):
    name = models.CharField(max_length=150)
    team1 = models.ForeignKey(Roster, related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Roster, related_name='team2', on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return '{name} ({team1} vs {team2})'.format(
            name=self.name,
            team1=self.team1,
            team2=self.team2
        ) 

basket/forms.py
from django import forms
from .models import Team, Player, Coach
from django.contrib.auth.models import User

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'

class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'

class UserUpdateForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username']

basket/views.py
from django.shortcuts import render, redirect
from basket.models import Coach, Team, Player, Roster, Match
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from basket.forms import TeamForm, PlayerForm, CoachForm, UserUpdateForm
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

@login_required #se requiere un login para ver esta pagina
#listar los últimos 5 partidos planificados y los 5 últimos jugadores incorporados a algún equipo. Además debe mostrar la cantidad de jugadores incritos por cada equipo.
def list(request):
	data = {}
	template_name = 'basket/home.html'
	data['last_matches'] = Match.objects.order_by('id').filter(Q(team1__team__coach__user=request.user) | Q(team2__team__coach__user=request.user)).reverse()[:3]
	data['last_matches_superuser'] = Match.objects.order_by('id').reverse()[:3]
	data['last_players'] = Player.objects.order_by('id').filter(team__coach__user=request.user).reverse()[:3]
	data['last_players_superuser'] = Player.objects.order_by('id').all().reverse()[:3]
	data['last_coaches'] = Coach.objects.order_by('id').reverse()[:3]

	return render(request, template_name, data)


@login_required
def team_list(request): #listar todos los equipos registrados en una tabla con paginación.
	data = {}
	template_name = 'basket/teams.html'

	page = request.GET.get('page', 1)
	team_lists = Team.objects.filter(coach__user=request.user)
	paginator = Paginator(team_lists, 2)

	try:
		data['teams'] = paginator.page(page)
	except PageNotAnInteger:
		data['teams'] = paginator.page(1)
	except EmptyPage:
		data['teams'] = paginator.page(paginator.num_pages)


	return render(request, template_name, data)

@login_required
def player_list(request): #listar todos los jugadores agrupados por equipo. Los jugadores deben ser listados a través de una tabla.
	data = {}
	template_name = 'basket/players.html'
	data['teams'] = Team.objects.filter(coach__user=request.user)

	return render(request, template_name, data)

@login_required
def coach_list(request): #listar una tabla con todos los entrenadores registrados e indicar a que equipo pertenece.
	data = {}
	template_name = 'basket/coach.html'
	data["coachs"] = Coach.objects.filter(user=request.user)

	return render(request, template_name, data)

@login_required
def match_list(request): #listar (no necesariamente en una tabla). los partidos registrados. Debe indicar que equipo se enfrenta contra quien y cuando.
	data = {}
	template_name = 'basket/match.html'
	data['matches'] = Match.objects.filter(Q(team1__team__coach__user=request.user) | Q(team2__team__coach__user=request.user))

	return render(request, template_name, data)



@permission_required('basket.add_team')
def create_team(request):
	data = {}
	template_name = 'basket/create_team.html'

	if request.method == 'POST':
		data['form'] = TeamForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save() #si el formulario es valido lo guardo
			return redirect('basket:team_list')
	else:
		data['form'] = TeamForm()

	return render(request, template_name, data)

@permission_required('basket.change_team')
def update_team(request, team_id):
	data = {}
	template_name = 'basket/update_team.html'
	team = Team.objects.get(pk=team_id)

	if request.method == 'POST':
		data['form'] = TeamForm(request.POST,request.FILES or None, instance=team)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('basket:team_list')
	else:
		data['form'] = TeamForm(instance=team)

	return render(request, template_name, data)

@permission_required('basket.delete_team')
def delete_team(request, team_id):
	data = {}
	template_name = 'basket/delete_team.html'
	data['team'] = Team.objects.get(pk=team_id)

	if request.method == 'POST':
		data['team'].delete()
		return redirect('basket:team_list')

	return render(request, template_name, data)


@permission_required('basket.add_player')
def create_player(request):
	data = {}
	template_name = 'basket/create_player.html'

	if request.method == 'POST':
		data['form'] = PlayerForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('basket:player_list')
	else:
		data['form'] = PlayerForm()

	return render(request, template_name, data)

@permission_required('basket.change_player')
def update_player(request, player_id):
	data = {}
	template_name = 'basket/update_player.html'
	player = Player.objects.get(pk=player_id)

	if request.method == 'POST':
		data['form'] = PlayerForm(request.POST,files=request.FILES, instance=player)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('basket:player_list')
	else:
		data['form'] = PlayerForm(instance=player)

	return render(request, template_name, data)

@permission_required('basket.delete_player')
def delete_player(request, player_id):
	data = {}
	template_name = 'basket/delete_player.html'
	data['player'] = Player.objects.get(pk=player_id)

	if request.method == 'POST':
		data['player'].delete()
		return redirect('basket:player_list')

	return render(request, template_name, data)


@permission_required('basket.add_coach')
def create_coach(request):
	data = {}
	template_name = 'basket/create_coach.html'

	if request.method == 'POST':
		data['form'] = CoachForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('basket:coach_list')
	else:
		data['form'] = CoachForm()

	return render(request, template_name, data)

@permission_required('basket.change_coach')
def update_coach(request, coach_id):
	data = {}
	template_name = 'basket/update_coach.html'
	coach = Coach.objects.get(pk=coach_id)

	if request.method == 'POST':
		data['form'] = CoachForm(request.POST,files=request.FILES, instance=coach)
		data['userform'] = UserUpdateForm(request.POST, instance=request.user)
		if data['form'].is_valid() and data['userform'].is_valid():
			data['form'].save()
			data['userform'].save()
			return redirect('basket:coach_list')
	else:
		data['form'] = CoachForm(instance=coach)
		data['userform'] = UserUpdateForm(instance=request.user)

	return render(request, template_name, data)

@permission_required('basket.change_coach')
def update_coach_password(request):
	data = {}
	template_name = 'basket/update_coach_password.html'
	#data['coach'] = Coach.objects.get(pk=coach_id)

	if request.method == 'POST':
		data['form'] = PasswordChangeForm(data=request.POST, user=request.user)
		if data['form'].is_valid():
			data['form'].save()
			update_session_auth_hash(request, data['form'].user)
			return redirect('basket:coach_list')
	else:
		data['form'] = PasswordChangeForm(user=request.user)

	return render(request, template_name, data)

@permission_required('basket.delete_coach')
def delete_coach(request, coach_id):
	data = {}
	template_name = 'basket/delete_coach.html'
	data['coach'] = Coach.objects.get(pk=coach_id)

	if request.method == 'POST':
		data['coach'].delete()
		return redirect('basket:coach_list')

	return render(request, template_name, data)

basket/templates/basket/base.html
<!doctype html>
<html lang="es-cl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- fontawesomecdn -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">

    <style>
      .breadcrumb {
        background: white;
        padding-left: 0rem;
      }
      /*a serian todos los tipo link*/
      .breadcrumb a {
        color: black;
      }
      .bg-dark-primary {
        background-color: #444!important;
        margin: 0;
        padding: 0;
      }
      .bg-dark-primary .container {
        color: #9a9793
      }
      .bg-dark-primary .container p {
        width: 100%;
        text-align: right;
        margin-bottom: 0;
      }
    </style>

    {% block extra_css %}
    {% endblock %}

    <title>{% block title %}Basket app{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark-primary">
      <div class="container">
        <p>Usuario: <strong>{{request.user}}</strong> | <a href="{% url 'auth:logout' %}">Cerrar sesion <i class="fas fa-sign-out-alt"></i></a></p>
      </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container">
        <a class="navbar-brand" href="#">BasketApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              {% block active_navbar_basket %}<a class="nav-link" href="{% url 'basket:list' %}">Basket</a>{% endblock %}
            </li>

            <li class="nav-item">
              {% block active_navbar_team %}<a class="nav-link" href="{% url 'basket:team_list' %}">Equipos</a>{% endblock %}
            </li>

            <li class="nav-item">
              {% block active_navbar_player %}<a class="nav-link" href="{% url 'basket:player_list' %}">Jugadores</a>{% endblock %}
            </li>

            <li class="nav-item">
              {% block active_navbar_coach %}<a class="nav-link" href="{% url 'basket:coach_list' %}">Entrenadores</a>{% endblock %}
            </li>

            <li class="nav-item">
              {% block active_navbar_match %}<a class="nav-link" href="{% url 'basket:match_list' %}">Partidos</a>{% endblock %}
            </li>
          </ul>
        </div>

      </div>
    </nav>

    <div class="container">
      {% block content_head %}
      {% endblock %}

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'basket:list' %}"><i class="fas fa-home"></i> Basket</a></li>
          {% block breadcrumb %}
          {% endblock %}
        </ol>
      </nav>

      {% block content_body %}
      {% endblock %}            
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

basket/templates/basket/coach.html
{% extends "basket/base.html" %}

	{% block title %}
	Jugadores
	{% endblock %}

	{% block active_navbar_coach %}<a class="nav-link active" href="{% url 'basket:coach_list' %}">Entrenadores</a>{% endblock %}

  {% block extra_css %}
  <style>
    .color_update {
      color: #DCD900;
      font-size: 19px;
    }
    .color_delete {
      color: #DC1700;
      font-size: 19px;
    }
  </style>
  {% endblock %}

	{% block content_head %}
	<!-- bloque titulo -->
	  <div class="row mt-2">
	    <div class="col-sm-6 col-md-8 col-lg-10">
	      <h2>Entrenadores</h2>
	    </div>
	    <div class="col-sm-6 col-md-4 col-lg-2">
	      {% if request.user.is_superuser %}
		  <a href="{% url 'basket:create_coach' %}" class="btn btn-success btn-block">Crear entrenador</a>
		  {% endif %}
	    </div>
	  </div>
	<!-- fin bloque titulo -->
	{% endblock %}

  {% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Entrenadores</li>
  {% endblock %}

	{% block content_body %}
	<!-- bloque tabla -->
	  <div class="row">
	    <div class="col-md">
	      <table class="table table-striped table-hover mt-5">
	      	<thead>
		  	  <tr>
	      	  <th>Coach</th>
		        <th>Equipo</th>
		        <th>Accion</th>
		      </tr>
		  	</thead>

		  	<tbody>
		  	  {% for coach in coachs %}
		  	  	<tr>
	            <td style="width:150px;">{{coach.name}}</td>
	            <td style="width:150px;">{{coach.team.name}}</td>
	            <td style="width:50px;">
	            	<a href="{% url 'basket:update_coach' coach.id %}">Editar <i class="fas fa-edit color_update"></i></a>
	            	{% if request.user.is_superuser %}
	            	 | 
	            	<a href="{% url 'basket:delete_coach' coach.id %}">Eliminar <i class="fas fa-trash-alt color_delete"></i></a>
	            	{% endif %}
	          	</td>
	   	  	  </tr>
	   	  	  {% endfor %}
		    </tbody>
		  </table>

	    </div>
	  </div>
	<!-- fin bloque tabla -->
	{% endblock %}

basket/templates/basket/home.html
{% extends "basket/base.html" %}

      {% block title %}
      Home
      {% endblock %}

      {% block active_navbar_basket %}<a class="nav-link active" href="{% url 'basket:list' %}">Basket</a>{% endblock %}

      {% block content_head %}
      <h2>Aplicacion basket</h2>
      {% endblock %}

      {% block breadcrumb %}
      {% endblock %}

      {% block content_body %}
      <div class="row">
        <div class="col">
          <h2>Datos del entrenador</h2>
            <ul>
              <li><a class="nav-link active" href="{% url 'basket:team_list' %}">Equipo</a></li>
              <li><a class="nav-link active" href="{% url 'basket:player_list' %}">Jugadores</a></li>
              <li><a class="nav-link active" href="{% url 'basket:match_list' %}">Partidos</a></li>
            </ul>
        </div>
      </div>
      
      <div class="row">
        {% if not request.user.is_superuser %}
        <div class="col-md-4">
        <h2>Últimos 3 partidos planificados</h2>
        {% for match in last_matches %}
        <ul>
          <li>{{match.name}}</li>
        </ul>
        {% endfor %}
        </div>
        {% endif %}

        {% if request.user.is_superuser %}
        <div class="col-md-4">
        <h2>Últimos 3 partidos planificados</h2>
        {% for match in last_matches_superuser %}
        <ul>
          <li>{{match.name}}</li>
        </ul>
        {% endfor %}
        </div>
        {% endif %}

        {% if not request.user.is_superuser %}
        <div class="col-md-4">
        <h2>Últimos 3 jugadores incorporados</h2>
        {% for player in last_players %}
        <ul>
          <li>{{player.name}}</li>
        </ul>
        {% endfor %}
        </div>
        {% endif %}

        {% if request.user.is_superuser %}
        <div class="col-md-4">
        <h2>Últimos 3 jugadores incorporados</h2>
        {% for player in last_players_superuser %}
        <ul>
          <li>{{player.name}}</li>
        </ul>
        {% endfor %}
        </div>
        {% endif %}

        {% if request.user.is_superuser %}
        <div class="col-md-4">
        <h2>Ultimos 3 entrenadores incorporados al sistema</h2>
        {% for coach in last_coaches %}
        <ul>
          <li>{{coach.name}}</li>
        </ul>
        {% endfor %}
        </div>
        {% endif %}
      </div>
      {% endblock %}

basket/templates/basket/players.html
{% extends "basket/base.html" %}

	    {% block title %}
	    Jugadores
	    {% endblock %}

	    {% block active_navbar_player %}<a class="nav-link active" href="{% url 'basket:player_list' %}">Jugadores</a>{% endblock %}

      {% block extra_css %}
      <style>
      	.color_update {
      		color: #DCD900;
      		font-size: 19px;
      	}
      	.color_delete {
      		color: #DC1700;
      		font-size: 19px;
      	}
      </style>
      {% endblock %}

			{% block content_head %}
			<!-- bloque titulo -->
			  <div class="row mt-2">
			    <div class="col-sm-6 col-md-8 col-lg-10">
			      <h2>Jugadores agrupados por equipo</h2>
			    </div>
			    <div class="col-sm-6 col-md-4 col-lg-2">
			      {% if request.user.is_superuser %}
				  <a href="{% url 'basket:create_player' %}" class="btn btn-success btn-block">Crear Jugador</a>
				  {% endif %}
			    </div>
			  </div>
			<!-- fin bloque titulo -->
			{% endblock %}

      {% block breadcrumb %}
        <li class="breadcrumb-item active" aria-current="page">Jugadores</li>
      {% endblock %}

			{% block content_body %}
			<!-- bloque tabla -->
			  <div class="row">
			    <div class="col-md mt-5">
			    {% for team in teams %}
				  <h3>Equipo: {{team.name}}</h3>
			      <table class="table table-striped table-hover">
			      	<thead>
				  	  <tr>
			      	  <th>Jugadores</th>
			      	  <th>Accion</th>
				      </tr>
				  	  </thead>
						
						<tbody>
				  	  {% for player in team.player_set.all %}
				  	  <tr>
			            <td style="width:300px;">{{player.name}}</td>
			            <td style="width:50px;">
			            	<a href="{% url 'basket:update_player' player.id %}">Editar <i class="fas fa-edit color_update"></i></a>
			            	{% if request.user.is_superuser %}
			            	 |
			            	<a href="{% url 'basket:delete_player' player.id %}">Eliminar <i class="fas fa-trash-alt color_delete"></i></a>
			            	{% endif %}
			            </td>
			   	  	  </tr>
			   	  	{% endfor %}
				    </tbody>
				  </table>
				  {% endfor %}

			    </div>
			  </div>
			<!-- fin bloque tabla -->
			{% endblock %}

basket/templates/basket/teams.html
{% extends "basket/base.html" %}

      {% block title %}
      Equipos
      {% endblock %}

      {% block active_navbar_team %}<a class="nav-link active" href="{% url 'basket:team_list' %}">Equipos</a>{% endblock %}

      {% block extra_css %}
      <style>
      	.color_update {
      		color: #DCD900;
      		font-size: 19px;
      	}
      	.color_delete {
      		color: #DC1700;
      		font-size: 19px;
      	}
      </style>
      {% endblock %}

			{% block content_head %}
  	  <!-- bloque titulo -->
		  <div class="row mt-2">
		    <div class="col-sm-6 col-md-8 col-lg-10">
		      <h2>Lista de equipos registrados</h2>
		    </div>
		    <div class="col-sm-6 col-md-4 col-lg-2">
		    	{% if request.user.is_superuser %}
			  	<a href="{% url 'basket:create_team' %}" class="btn btn-success btn-block">Crear Team</a>
			  	{% endif %}
		    </div>
		  </div>
		  <!-- fin bloque titulo -->
		  {% endblock %}

      {% block breadcrumb %}
        <li class="breadcrumb-item active" aria-current="page">Equipos</li>
      {% endblock %}

      {% block content_body %}
		  <!-- bloque tabla -->
		  <div class="row">
		    <div class="col-md">

		      <table class="table table-striped table-hover mt-5">
		      	<thead>
			  	  <tr>
		      	    <th>Equipo</th>
		      	    <th>Accion</th>
			      </tr>
			  	</thead>

			  	<tbody>
			  	    {% for team in teams %}
			  	    <tr>
		            <td style="width:300px;">{{team.name}}</td>
		            <td style="width:50px;">
		            	<a href="{% url 'basket:update_team' team.id %}">Editar <i class="fas fa-edit color_update"></i></a>
		            	{% if request.user.is_superuser %}
		            	 | 
		            	<a href="{% url 'basket:delete_team' team.id %}">Eliminar <i class="fas fa-trash-alt color_delete"></i></a>
		            	{% endif %}
		            </td>
		   	  	  </tr>
		   	  	  {% endfor %}
			    </tbody>
			  </table>


			  {% if teams.has_other_pages %}
			  <nav aria-label="Page navigation">
			    <ul class="pagination">
			      {% if teams.has_previous %}
			        <li class="page-item"><a href="?page={{ teams.previous_page_number }}" class="page-link">&laquo;</a></li>
			      {% else %}
			        <li class="page-item" class="disabled"><span class="page-link">&laquo;</span></li>
			      {% endif %}

			      {% for i in teams.paginator.page_range %}
			        {% if teams.number == i %}
			          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
			        {% else %}
			          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
			        {% endif %}
			      {% endfor %}

			      {% if teams.has_next %}
			        <li><a href="?page={{ teams.next_page_number }}" class="page-link">&raquo;</a></li>
			      {% else %}
			        <li class="disabled"><span class="page-link">&raquo;</span></li>
			      {% endif %}
			    </ul>
			  {% endif %}
			  </nav>

		    </div>
		  </div>
		  <!-- fin bloque tabla -->
      {% endblock %}

basket/templates/basket/update_coach.html
{% extends "basket/base.html" %}
{% load bootstrap4 %}

  {% block title %}
  Editar coach
  {% endblock %}

  {% block active_navbar_coach %}<a class="nav-link active" href="{% url 'basket:coach_list' %}">Entrenadores</a>{% endblock %}

  {% block content_head %}
	<h2>Editar Coach:</h2>
	{% endblock %}

  {% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'basket:coach_list' %}">Entrenadores</a></li>
    <li class="breadcrumb-item active" aria-current="page">Editar entrenador</li>
  {% endblock %}

	{% bootstrap_messages %}
	
	{% block content_body %}
	<a href="{% url 'basket:update_coach_password' %}" class="btn btn-success btn-block">Cambiar contraseña</a>
	<form class="" method="post" enctype="multipart/form-data">
	  {% csrf_token %}
	  	{% bootstrap_form userform %}
		{% bootstrap_form form %}
		{% buttons %}
	    <button type="submit" class="btn btn-primary btn-lg">
	      <i class="fas fa-edit"></i> Editar coach
	    </button>
	  {% endbuttons %}
	</form>
	{% endblock %}